version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/var/lib/redis/data
  api:
    build: .
    image: 'mcgi-prod-tools:${TAG}'
    restart: always
    environment:
      - DB_HOST=db
      - PORT=${API_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_LYRICS_BUCKET=${AWS_S3_LYRICS_BUCKET}
      - REDIS_URL=redis://cache:6379
      - SIDEKIQ_USERNAME=${SIDEKIQ_USERNAME}
      - SIDEKIQ_PASSWORD=${SIDEKIQ_PASSWORD}
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "5000:5000"
    depends_on:
      - cache
      - db
volumes:
  dbdata:
  cache:
