version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=ABC12abc
      - PORT=5000
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  api:
    build: .
    image: 'mcgi-prod-tools:${TAG}'
    environment:
      - DB_HOST=db
      - PORT=5000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_LYRICS_BUCKET=${AWS_S3_LYRICS_BUCKET}
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - appdir:/app

volumes:
  dbdata:
  appdir:
