version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=ABC12abc
      - PORT=5000
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  web:
    image: 'mcgi-prod-tools:latest'
    environment:
      - DB_HOST=db
      - BASE_URL=http://192.168.0.120:5000
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  dbdata:
